### ISSUE TITLE
Unable to get around default mappings

### ISSUE THREAD

**Issue by resolritter** [inkarkat/vim-UnconditionalPaste#1]
Heya! I've decided to override my p/P keys with the ones from this plug-in instead, but 

https://github.com/inkarkat/vim-UnconditionalPaste/blob/master/plugin/UnconditionalPaste.vim#L160

indicates that this isn't possible with the hardcoded g prefix.

---

So I tried the suggested approach of using my own <Plug> setup and defining

`let g:UnconditionalPaste_Mappings = []`

which isn't mentioned in the documentation! Still, it doesn't seem like there is a check for when the user defines this variable. My suggestion would be to change

https://github.com/inkarkat/vim-UnconditionalPaste/blob/master/plugin/UnconditionalPaste.vim#L62

to

```
if ! exists('g:UnconditionalPaste_Mappings')
    let g:UnconditionalPaste_Mappings = [
    ....
```

However, there seems to be some magic in there about setting up variables based on the mappings, so this approach would maybe obstruct some functionality. Is there a better way of giving more configuration flexibility while also dropping the prefix g?

**Comment by resolritter** [comment]
After coming back and trying to use this option with an empty list

`let g:UnconditionalPaste_DefaultMappings = []`

I noticed it hadn't generated the \<Plug> mappings. So I thought about another variable called _g:UnconditionalPaste_EnabledMappings_ for skipping the nmap step, or  _g:UnconditionalPaste_DefaultPrefix_ for swapping the g out of that expression.

https://github.com/inkarkat/vim-UnconditionalPaste/blob/master/plugin/UnconditionalPaste.vim#L159

I figured after looking at the source that I could map the unwanted default mappings to *\<Plug>Disabled* and they would probably disappear, but the list is so extensive for the three modes that it gets a bit unwieldy to do that one by one. I'm also not sure if all that mapping/remapping adds bit more of a delay in Vim's startup time, so is it not better to skip it altogether if they won't be used anyway? :thinking:

**Comment by inkarkat** [comment]
The `g:UnconditionalPaste_Mappings` variable is not a configuration (though it looks like one), that's why it isn't documented. I need this information in a variable to be able to build the help in the `ghp` mapping.

The plugin uses the canonical `hasmapto()` check for the `<Plug>`-mappings, so if a different mapping has already been defined, the default ones (that all start with `g`) are skipped. As you've correctly found out, by mapping to `<Plug>Disabled...`, you can completely disable those mappings that you don't want.

If you're only interested in a few mappings, that indeed can be a hassle. (I wouldn't worry about the startup performance too much; those checks are simple dictionary lookups, and the loop to define the `<Plug>`-mappings has to run, anyway.)

Therefore, I've just introduced a `g:UnconditionalPaste_no_mappings` configuration flag that (if set) allows you to completely skip _all_ default mappings.

So, for example, if you just want to override the default `p`/`P` mappings to always be characterwise:

    let g:UnconditionalPaste_no_mappings = 1
    nmap P <Plug>UnconditionalPasteCharBefore
    nmap p <Plug>UnconditionalPasteCharAfter

I hope that suits your needs. Thank you for the valuable feedback, and happy Vimming!
